//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aceka.web_ui.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EndofLinEntities : DbContext
    {
        public EndofLinEntities()
            : base("name=EndofLinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MarsanMail> MarsanMail { get; set; }
        public virtual DbSet<MarsanMailHesaplari> MarsanMailHesaplari { get; set; }
        public virtual DbSet<MarsanMailOrme> MarsanMailOrme { get; set; }
    }
}
