//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aceka.web_ui.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarsanMailOrme
    {
        public int sipid { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<System.DateTime> TerminTarihi { get; set; }
        public Nullable<System.DateTime> OrmeTerminTarihi { get; set; }
        public string Firma { get; set; }
        public string FirmaSiparisNo { get; set; }
        public Nullable<decimal> IsEmriMiktari { get; set; }
        public Nullable<decimal> IsEmriBakiye { get; set; }
        public Nullable<decimal> UretimMiktari { get; set; }
        public Nullable<decimal> UretimBakiye { get; set; }
        public string Cinsi { get; set; }
        public Nullable<double> SiparisMiktari { get; set; }
        public string Birim { get; set; }
        public string Aciklama { get; set; }
        public string Pus { get; set; }
        public string Fayn { get; set; }
        public string TüpMay { get; set; }
    }
}
