//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aceka.web_ui.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarsanMail
    {
        public int sipid { get; set; }
        public string SiparisNo { get; set; }
        public Nullable<System.DateTime> TerminTarihi { get; set; }
        public string Firma { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string FirmaSiparisNo { get; set; }
        public string Renk { get; set; }
        public string StokKodu { get; set; }
        public Nullable<double> SiparisMiktari { get; set; }
        public string Durum { get; set; }
        public string Talimat { get; set; }
        public Nullable<int> ReceteNo { get; set; }
        public Nullable<int> KartNo { get; set; }
        public Nullable<decimal> IsEmriMiktari { get; set; }
        public Nullable<decimal> DepoMiktari { get; set; }
        public Nullable<int> TopSayisi { get; set; }
        public string UretilmemisMiktar { get; set; }
        public Nullable<System.DateTime> SonHaraketTarihi { get; set; }
    }
}
