//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aceka.web_ui.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarsanMailHesaplari
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string EPosta { get; set; }
        public bool Aktif { get; set; }
        public bool OrmeAktif { get; set; }
    }
}
